config/routes.rb
Rails.application.routes.draw do
  resources :sprinkle_events
  resources :water_managers
  resources :sprinkles
  resources :histories
  resources :valves
  mount Hyperloop::Engine => '/hyperloop'
  # root 'hyperloop#app' # route just the root to the component named App
  get '/(*other)', to: 'hyperloop#app' # route everything to the App component
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/water_managers_controller.rb
class WaterManagersController < ApplicationController
  before_action :set_water_manager, only: [:show, :edit, :update, :destroy]

  # GET /water_managers
  # GET /water_managers.json
  def index
    @water_managers = WaterManager.all
  end

  # GET /water_managers/1
  # GET /water_managers/1.json
  def show
  end

  # GET /water_managers/new
  def new
    @water_manager = WaterManager.new
  end

  # GET /water_managers/1/edit
  def edit
  end

  # POST /water_managers
  # POST /water_managers.json
  def create
    @water_manager = WaterManager.new(water_manager_params)

    respond_to do |format|
      if @water_manager.save
        format.html { redirect_to @water_manager, notice: 'Water manager was successfully created.' }
        format.json { render :show, status: :created, location: @water_manager }
      else
        format.html { render :new }
        format.json { render json: @water_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /water_managers/1
  # PATCH/PUT /water_managers/1.json
  def update
    respond_to do |format|
      if @water_manager.update(water_manager_params)
        format.html { redirect_to @water_manager, notice: 'Water manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @water_manager }
      else
        format.html { render :edit }
        format.json { render json: @water_manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /water_managers/1
  # DELETE /water_managers/1.json
  def destroy
    @water_manager.destroy
    respond_to do |format|
      format.html { redirect_to water_managers_url, notice: 'Water manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_water_manager
      @water_manager = WaterManager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def water_manager_params
      params.require(:water_manager).permit(:state, :http_host)
    end
end

app/helpers/water_managers_helper.rb
module WaterManagersHelper
end

app/views/water_managers/_form.html.erb
<%= form_with(model: water_manager, local: true) do |form| %>
  <% if water_manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(water_manager.errors.count, "error") %> prohibited this water_manager from being saved:</h2>

      <ul>
      <% water_manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :water_manager_state %>
  </div>

  <div class="field">
    <%= form.label :http_host %>
    <%= form.text_field :http_host, id: :water_manager_http_host %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/water_managers/edit.html.erb
<h1>Editing Water Manager</h1>

<%= render 'form', water_manager: @water_manager %>

<%= link_to 'Show', @water_manager %> |
<%= link_to 'Back', water_managers_path %>

app/views/water_managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Water Managers</h1>

<table>
  <thead>
    <tr>
      <th>State</th>
      <th>Http host</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @water_managers.each do |water_manager| %>
      <tr>
        <td><%= water_manager.state %></td>
        <td><%= water_manager.http_host %></td>
        <td><%= link_to 'Show', water_manager %></td>
        <td><%= link_to 'Edit', edit_water_manager_path(water_manager) %></td>
        <td><%= link_to 'Destroy', water_manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Water Manager', new_water_manager_path %>

app/views/water_managers/new.html.erb
<h1>New Water Manager</h1>

<%= render 'form', water_manager: @water_manager %>

<%= link_to 'Back', water_managers_path %>

app/views/water_managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>State:</strong>
  <%= @water_manager.state %>
</p>

<p>
  <strong>Http host:</strong>
  <%= @water_manager.http_host %>
</p>

<%= link_to 'Edit', edit_water_manager_path(@water_manager) %> |
<%= link_to 'Back', water_managers_path %>