config/routes.rb
Rails.application.routes.draw do
  resources :sprinkle_events
  resources :water_managers
  resources :sprinkles
  resources :histories
  resources :valves
  mount Hyperloop::Engine => '/hyperloop'
  # root 'hyperloop#app' # route just the root to the component named App
  get '/(*other)', to: 'hyperloop#app' # route everything to the App component
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/valves_controller.rb
class ValvesController < ApplicationController
  before_action :set_valve, only: [:show, :edit, :update, :destroy]

  # GET /valves
  # GET /valves.json
  def index
    @valves = Valve.all
  end

  # GET /valves/1
  # GET /valves/1.json
  def show
  end

  # GET /valves/new
  def new
    @valve = Valve.new
  end

  # GET /valves/1/edit
  def edit
  end

  # POST /valves
  # POST /valves.json
  def create
    @valve = Valve.new(valve_params)

    respond_to do |format|
      if @valve.save
        format.html { redirect_to @valve, notice: 'Valve was successfully created.' }
        format.json { render :show, status: :created, location: @valve }
      else
        format.html { render :new }
        format.json { render json: @valve.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valves/1
  # PATCH/PUT /valves/1.json
  def update
    respond_to do |format|
      if @valve.update(valve_params)
        format.html { redirect_to @valve, notice: 'Valve was successfully updated.' }
        format.json { render :show, status: :ok, location: @valve }
      else
        format.html { render :edit }
        format.json { render json: @valve.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valves/1
  # DELETE /valves/1.json
  def destroy
    @valve.destroy
    respond_to do |format|
      format.html { redirect_to valves_url, notice: 'Valve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valve
      @valve = Valve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valve_params
      params.require(:valve).permit(:name, :gpio_pin, :cpu2bb_color, :bb_pin, :bb2relay_color, :relay_module, :relay_index, :relay2valve_color, :cmd, :base_time)
    end
end

app/helpers/valves_helper.rb
module ValvesHelper
end

app/views/valves/_form.html.erb
<%= form_with(model: valve, local: true) do |form| %>
  <% if valve.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valve.errors.count, "error") %> prohibited this valve from being saved:</h2>

      <ul>
      <% valve.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :valve_name %>
  </div>

  <div class="field">
    <%= form.label :gpio_pin %>
    <%= form.number_field :gpio_pin, id: :valve_gpio_pin %>
  </div>

  <div class="field">
    <%= form.label :cpu2bb_color %>
    <%= form.text_field :cpu2bb_color, id: :valve_cpu2bb_color %>
  </div>

  <div class="field">
    <%= form.label :bb_pin %>
    <%= form.number_field :bb_pin, id: :valve_bb_pin %>
  </div>

  <div class="field">
    <%= form.label :bb2relay_color %>
    <%= form.text_field :bb2relay_color, id: :valve_bb2relay_color %>
  </div>

  <div class="field">
    <%= form.label :relay_module %>
    <%= form.number_field :relay_module, id: :valve_relay_module %>
  </div>

  <div class="field">
    <%= form.label :relay_index %>
    <%= form.number_field :relay_index, id: :valve_relay_index %>
  </div>

  <div class="field">
    <%= form.label :relay2valve_color %>
    <%= form.text_field :relay2valve_color, id: :valve_relay2valve_color %>
  </div>

  <div class="field">
    <%= form.label :cmd %>
    <%= form.number_field :cmd, id: :valve_cmd %>
  </div>

  <div class="field">
    <%= form.label :base_time %>
    <%= form.datetime_select :base_time, id: :valve_base_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/valves/edit.html.erb
<h1>Editing Valve</h1>

<%= render 'form', valve: @valve %>

<%= link_to 'Show', @valve %> |
<%= link_to 'Back', valves_path %>

app/views/valves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Valves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gpio pin</th>
      <th>Cpu2bb color</th>
      <th>Bb pin</th>
      <th>Bb2relay color</th>
      <th>Relay module</th>
      <th>Relay index</th>
      <th>Relay2valve color</th>
      <th>Cmd</th>
      <th>Base time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valves.each do |valve| %>
      <tr>
        <td><%= valve.name %></td>
        <td><%= valve.gpio_pin %></td>
        <td><%= valve.cpu2bb_color %></td>
        <td><%= valve.bb_pin %></td>
        <td><%= valve.bb2relay_color %></td>
        <td><%= valve.relay_module %></td>
        <td><%= valve.relay_index %></td>
        <td><%= valve.relay2valve_color %></td>
        <td><%= valve.cmd %></td>
        <td><%= valve.base_time %></td>
        <td><%= link_to 'Show', valve %></td>
        <td><%= link_to 'Edit', edit_valve_path(valve) %></td>
        <td><%= link_to 'Destroy', valve, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valve', new_valve_path %>

app/views/valves/new.html.erb
<h1>New Valve</h1>

<%= render 'form', valve: @valve %>

<%= link_to 'Back', valves_path %>

app/views/valves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @valve.name %>
</p>

<p>
  <strong>Gpio pin:</strong>
  <%= @valve.gpio_pin %>
</p>

<p>
  <strong>Cpu2bb color:</strong>
  <%= @valve.cpu2bb_color %>
</p>

<p>
  <strong>Bb pin:</strong>
  <%= @valve.bb_pin %>
</p>

<p>
  <strong>Bb2relay color:</strong>
  <%= @valve.bb2relay_color %>
</p>

<p>
  <strong>Relay module:</strong>
  <%= @valve.relay_module %>
</p>

<p>
  <strong>Relay index:</strong>
  <%= @valve.relay_index %>
</p>

<p>
  <strong>Relay2valve color:</strong>
  <%= @valve.relay2valve_color %>
</p>

<p>
  <strong>Cmd:</strong>
  <%= @valve.cmd %>
</p>

<p>
  <strong>Base time:</strong>
  <%= @valve.base_time %>
</p>

<%= link_to 'Edit', edit_valve_path(@valve) %> |
<%= link_to 'Back', valves_path %>