config/routes.rb
Rails.application.routes.draw do
  resources :sprinkle_events
  resources :water_managers
  resources :sprinkles
  resources :histories
  resources :valves
  mount Hyperloop::Engine => '/hyperloop'
  # root 'hyperloop#app' # route just the root to the component named App
  get '/(*other)', to: 'hyperloop#app' # route everything to the App component
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/sprinkles_controller.rb
class SprinklesController < ApplicationController
  before_action :set_sprinkle, only: [:show, :edit, :update, :destroy]

  # GET /sprinkles
  # GET /sprinkles.json
  def index
    @sprinkles = Sprinkle.all
  end

  # GET /sprinkles/1
  # GET /sprinkles/1.json
  def show
  end

  # GET /sprinkles/new
  def new
    @sprinkle = Sprinkle.new
  end

  # GET /sprinkles/1/edit
  def edit
  end

  # POST /sprinkles
  # POST /sprinkles.json
  def create
    @sprinkle = Sprinkle.new(sprinkle_params)

    respond_to do |format|
      if @sprinkle.save
        format.html { redirect_to @sprinkle, notice: 'Sprinkle was successfully created.' }
        format.json { render :show, status: :created, location: @sprinkle }
      else
        format.html { render :new }
        format.json { render json: @sprinkle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sprinkles/1
  # PATCH/PUT /sprinkles/1.json
  def update
    respond_to do |format|
      if @sprinkle.update(sprinkle_params)
        format.html { redirect_to @sprinkle, notice: 'Sprinkle was successfully updated.' }
        format.json { render :show, status: :ok, location: @sprinkle }
      else
        format.html { render :edit }
        format.json { render json: @sprinkle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sprinkles/1
  # DELETE /sprinkles/1.json
  def destroy
    @sprinkle.destroy
    respond_to do |format|
      format.html { redirect_to sprinkles_url, notice: 'Sprinkle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sprinkle
      @sprinkle = Sprinkle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sprinkle_params
      params.require(:sprinkle).permit(:next_start_time, :base_start_time, :time_input, :duration, :valve_id)
    end
end

app/helpers/sprinkles_helper.rb
module SprinklesHelper
end

app/views/sprinkles/_form.html.erb
<%= form_with(model: sprinkle, local: true) do |form| %>
  <% if sprinkle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sprinkle.errors.count, "error") %> prohibited this sprinkle from being saved:</h2>

      <ul>
      <% sprinkle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :next_start_time %>
    <%= form.datetime_select :next_start_time, id: :sprinkle_next_start_time %>
  </div>

  <div class="field">
    <%= form.label :base_start_time %>
    <%= form.datetime_select :base_start_time, id: :sprinkle_base_start_time %>
  </div>

  <div class="field">
    <%= form.label :time_input %>
    <%= form.text_field :time_input, id: :sprinkle_time_input %>
  </div>

  <div class="field">
    <%= form.label :duration %>
    <%= form.number_field :duration, id: :sprinkle_duration %>
  </div>

  <div class="field">
    <%= form.label :valve_id %>
    <%= form.number_field :valve_id, id: :sprinkle_valve_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sprinkles/edit.html.erb
<h1>Editing Sprinkle</h1>

<%= render 'form', sprinkle: @sprinkle %>

<%= link_to 'Show', @sprinkle %> |
<%= link_to 'Back', sprinkles_path %>

app/views/sprinkles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sprinkles</h1>

<table>
  <thead>
    <tr>
      <th>Next start time</th>
      <th>Base start time</th>
      <th>Time input</th>
      <th>Duration</th>
      <th>Valve</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sprinkles.each do |sprinkle| %>
      <tr>
        <td><%= sprinkle.next_start_time %></td>
        <td><%= sprinkle.base_start_time %></td>
        <td><%= sprinkle.time_input %></td>
        <td><%= sprinkle.duration %></td>
        <td><%= sprinkle.valve_id %></td>
        <td><%= link_to 'Show', sprinkle %></td>
        <td><%= link_to 'Edit', edit_sprinkle_path(sprinkle) %></td>
        <td><%= link_to 'Destroy', sprinkle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sprinkle', new_sprinkle_path %>

app/views/sprinkles/new.html.erb
<h1>New Sprinkle</h1>

<%= render 'form', sprinkle: @sprinkle %>

<%= link_to 'Back', sprinkles_path %>

app/views/sprinkles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Next start time:</strong>
  <%= @sprinkle.next_start_time %>
</p>

<p>
  <strong>Base start time:</strong>
  <%= @sprinkle.base_start_time %>
</p>

<p>
  <strong>Time input:</strong>
  <%= @sprinkle.time_input %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @sprinkle.duration %>
</p>

<p>
  <strong>Valve:</strong>
  <%= @sprinkle.valve_id %>
</p>

<%= link_to 'Edit', edit_sprinkle_path(@sprinkle) %> |
<%= link_to 'Back', sprinkles_path %>